import {
  VideoUpscaler,
  ImageUpscaler,
  Anime4KShader,
  Anime4K_Clamp_Highlights,
  Anime4K_Restore_CNN_S,
  Anime4K_Restore_CNN_M,
  Anime4K_Restore_CNN_L,
  Anime4K_Restore_CNN_VL,
  Anime4K_Restore_CNN_UL,
  Anime4K_Restore_CNN_Soft_S,
  Anime4K_Restore_CNN_Soft_M,
  Anime4K_Restore_CNN_Soft_VL,
  Anime4K_Upscale_CNN_x2_S,
  Anime4K_Upscale_CNN_x2_M,
  Anime4K_Upscale_CNN_x2_L,
  Anime4K_Upscale_CNN_x2_VL,
  Anime4K_Upscale_CNN_x2_UL,
  Anime4K_Upscale_Denoise_CNN_x2_S,
  Anime4K_Upscale_Denoise_CNN_x2_M,
  Anime4K_Upscale_Denoise_CNN_x2_VL,
  Anime4K_AutoDownscalePre_x2,
  Anime4K_AutoDownscalePre_x4,
  ANIME4KJS_SIMPLE_S_2X,
  ANIME4KJS_SIMPLE_M_2X,
  ANIME4KJS_SIMPLE_L_2X,
  ANIME4KJS_SIMPLE_VL_2X,
  ANIME4KJS_SIMPLE_UL_2X,
  ANIME4K_HIGHEREND_MODE_A,
  ANIME4K_HIGHEREND_MODE_B,
  ANIME4K_HIGHEREND_MODE_C,
  ANIME4K_HIGHEREND_MODE_A_FAST,
  ANIME4K_LOWEREND_MODE_A,
  ANIME4K_LOWEREND_MODE_A_FAST,
  ANIME4K_LOWEREND_MODE_B,
  ANIME4K_LOWEREND_MODE_C,
} from "anime4k.js";

// Custom ultra-fast Denoise + Restore pipeline tuned for older compressed archives on Intel UHD 730
export const ANIME4KJS_SIMPLE_DENOISE_M_2X = [
  Anime4K_Clamp_Highlights,
  Anime4K_Upscale_Denoise_CNN_x2_M,
  Anime4K_Restore_CNN_M
];

export {
  VideoUpscaler,
  ImageUpscaler,
  Anime4KShader,
  ANIME4KJS_SIMPLE_S_2X,
  ANIME4KJS_SIMPLE_M_2X,
  ANIME4KJS_SIMPLE_L_2X,
  ANIME4KJS_SIMPLE_VL_2X,
  ANIME4KJS_SIMPLE_UL_2X,
  ANIME4K_HIGHEREND_MODE_A,
  ANIME4K_HIGHEREND_MODE_B,
  ANIME4K_HIGHEREND_MODE_C,
  ANIME4K_HIGHEREND_MODE_A_FAST,
  ANIME4K_LOWEREND_MODE_A,
  ANIME4K_LOWEREND_MODE_A_FAST,
  ANIME4K_LOWEREND_MODE_B,
  ANIME4K_LOWEREND_MODE_C,
};
